# Generated by Django 5.2 on 2026-01-14 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worships', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='worship',
            old_name='yt_link',
            new_name='Youtube_link',
        ),
        migrations.RenameField(
            model_name='worship',
            old_name='name',
            new_name='講員',
        ),
        migrations.RenameField(
            model_name='worship',
            old_name='hire_date',
            new_name='講道日期',
        ),
        migrations.RenameField(
            model_name='worship',
            old_name='description',
            new_name='講道題目',
        ),
        migrations.RemoveField(
            model_name='worship',
            name='is_mvp',
        ),
        migrations.RemoveField(
            model_name='worship',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='worship',
            name='photo',
        ),
    ]
