# Generated by Django 5.2 on 2026-01-15 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worships', '0002_rename_yt_link_worship_youtube_link_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='worship',
            options={'ordering': ['-講道日期']},
        ),
        migrations.AlterField(
            model_name='worship',
            name='講道日期',
            field=models.DateTimeField(),
        ),
        migrations.AddIndex(
            model_name='worship',
            index=models.Index(fields=['講道日期'], name='worships_wo_講道日期_78a7f4_idx'),
        ),
    ]
