# Generated by Django 5.2 on 2026-01-15 16:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worships', '0004_alter_worship_講道日期'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worship',
            name='講道日期',
            field=models.DateField(default=django.utils.timezone.now, help_text='Date this issue was/will be considered published'),
        ),
    ]
