# Generated by Django 5.2 on 2026-01-15 19:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worships', '0005_alter_worship_講道日期'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorshipSermon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speaker_name', models.CharField(max_length=100, verbose_name='講員')),
                ('sermon_title', models.CharField(max_length=200, verbose_name='講道題目')),
                ('youtube_link', models.URLField(verbose_name='YouTube連結')),
                ('sermon_date', models.DateField(default=django.utils.timezone.now, verbose_name='講道日期')),
            ],
            options={
                'verbose_name': '崇拜講道',
                'verbose_name_plural': '崇拜講道集',
                'ordering': ['-sermon_date'],
            },
        ),
        migrations.DeleteModel(
            name='Worship',
        ),
    ]
