# Generated by Django 5.2 on 2026-01-21 09:45

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('appl_deadline', models.DateField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('poster', models.ImageField(blank=True, null=True, upload_to='event_posters/')),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to hide this event from the public listing (e.g. draft, cancelled, postponed)', verbose_name='Active / Visible')),
                ('is_free', models.BooleanField(default=False, verbose_name='Free event')),
                ('fee_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Ticket price / Fee')),
                ('fee_currency', models.CharField(default='HKD', max_length=3)),
                ('early_bird_fee', models.DecimalField(blank=True, decimal_places=2, help_text='Optional discounted price', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Early bird price')),
                ('is_announcement', models.BooleanField(default=False, help_text='Check if this is just an informational poster/announcement (no registration allowed).', verbose_name='Informational only')),
                ('unlimited_quota', models.BooleanField(default=False, help_text='If checked, there is no limit on the number of participants', verbose_name='Unlimited quota')),
                ('quota_left', models.IntegerField(default=0, help_text='Number of available spots remaining. Only relevant if unlimited_quota is False.', verbose_name='Quota left')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event_id'], name='activities__event_i_4f8033_idx')],
            },
        ),
        migrations.CreateModel(
            name='EventParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Used as the main unique identifier per event', max_length=254, verbose_name='Registration email')),
                ('full_name', models.CharField(blank=True, help_text='Optional — may be collected during registration', max_length=255, verbose_name='Full name')),
                ('telephone', models.CharField(blank=True, help_text='Optional contact number', max_length=20, verbose_name='Telephone number')),
                ('registered_at', models.DateTimeField(auto_now_add=True, verbose_name='Registration date')),
                ('withdrawal_date', models.DateField(blank=True, help_text='Date when participant withdrew from the event', null=True, verbose_name='Withdrawal date')),
                ('notes', models.TextField(blank=True, help_text='Internal notes, special requests, etc.')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', related_query_name='participant', to='activities.event')),
                ('user', models.ForeignKey(blank=True, help_text='Filled automatically if registration was done while logged in', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_registrations', to=settings.AUTH_USER_MODEL, verbose_name='Registered user (optional)')),
            ],
            options={
                'verbose_name': 'Event Participant',
                'verbose_name_plural': 'Event Participants',
                'ordering': ['-registered_at'],
                'indexes': [models.Index(fields=['event', 'email'], name='activities__event_i_859f76_idx'), models.Index(fields=['user'], name='activities__user_id_b61e01_idx'), models.Index(fields=['registered_at'], name='activities__registe_f3377b_idx')],
                'unique_together': {('event', 'email')},
            },
        ),
    ]
