# Generated by Django 5.2 on 2026-01-14 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-event_id']},
        ),
        migrations.RemoveIndex(
            model_name='event',
            name='activities__start_d_36fb56_idx',
        ),
        migrations.RemoveIndex(
            model_name='event',
            name='activities__end_dat_26a015_idx',
        ),
        migrations.RemoveField(
            model_name='event',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='event',
            name='id',
        ),
        migrations.RemoveField(
            model_name='eventparticipant',
            name='paid',
        ),
        migrations.RemoveField(
            model_name='eventparticipant',
            name='payment_method',
        ),
        migrations.AddField(
            model_name='event',
            name='appl_deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='event_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='event',
            name='quota_left',
            field=models.IntegerField(default=0, help_text='Number of available spots remaining. Only relevant if unlimited_quota is False.', verbose_name='Quota left'),
        ),
        migrations.AddField(
            model_name='event',
            name='unlimited_quota',
            field=models.BooleanField(default=False, help_text='If checked, there is no limit on the number of participants', verbose_name='Unlimited quota'),
        ),
        migrations.AddField(
            model_name='eventparticipant',
            name='withdrawal_date',
            field=models.DateField(blank=True, help_text='Date when participant withdrew from the event', null=True, verbose_name='Withdrawal date'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['event_id'], name='activities__event_i_4f8033_idx'),
        ),
    ]
