# Generated by Django 5.2 on 2026-01-15 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_event_created_at_event_updated_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-created_at']},
        ),
    ]
