# Generated by Django 5.2 on 2026-01-15 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0004_alter_event_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Uncheck to hide this event from the public listing (e.g. draft, cancelled, postponed)', verbose_name='Active / Visible'),
        ),
    ]
