# Generated by Django 5.2 on 2026-01-15 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0005_event_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventparticipant',
            name='telephone',
            field=models.CharField(blank=True, help_text='Optional contact number', max_length=20, verbose_name='Telephone number'),
        ),
    ]
