# Generated by Django 5.2 on 2026-01-13 13:30

import django.utils.timezone
import newsletter.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="e.g. 'TechBit #42 - March 2025'", max_length=200)),
                ('slug', models.SlugField(help_text='Used in URLs - auto-generated recommended', max_length=120, unique=True)),
                ('published_date', models.DateField(default=django.utils.timezone.now, help_text='Date this issue was/will be considered published')),
                ('pdf_file', models.FileField(help_text='PDF version of the newsletter', upload_to=newsletter.models.newsletter_upload_path)),
                ('description', models.TextField(blank=True, help_text='Optional short summary / teaser (appears in archive)')),
                ('is_published', models.BooleanField(default=True, help_text='Uncheck to hide from public archive')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-published_date'],
                'get_latest_by': 'published_date',
                'indexes': [models.Index(fields=['-published_date'], name='newsletter__publish_0c116f_idx'), models.Index(fields=['is_published', 'published_date'], name='newsletter__is_publ_4e8667_idx')],
            },
        ),
    ]
