# Generated by Django 5.2 on 2026-01-16 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FellowshipEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='活動名稱')),
                ('date_text', models.CharField(blank=True, max_length=50, verbose_name='日期（文字）')),
                ('time_text', models.CharField(blank=True, max_length=50, verbose_name='時間')),
                ('location', models.CharField(blank=True, max_length=50, verbose_name='地點')),
                ('poster', models.ImageField(blank=True, null=True, upload_to='posters/', verbose_name='Poster')),
                ('description', models.TextField(blank=True, verbose_name='內容/簡介')),
                ('is_active', models.BooleanField(default=True, verbose_name='上架')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '聚會活動',
                'verbose_name_plural': '聚會活動',
                'ordering': ['sort_order', 'title'],
            },
        ),
    ]
