# Generated by Django 5.2.10 on 2026-01-27 03:37

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ministry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='標題')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('activity_date', models.DateField(default=django.utils.timezone.now, verbose_name='活動日期')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='地點')),
                ('image', models.ImageField(blank=True, null=True, upload_to='ministries/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'gif'])], verbose_name='圖片')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否顯示')),
                ('display_order', models.IntegerField(default=0, verbose_name='顯示順序')),
            ],
            options={
                'verbose_name': '事工動態',
                'verbose_name_plural': '事工動態',
                'ordering': ['-activity_date', 'display_order'],
            },
        ),
        migrations.CreateModel(
            name='Prayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='標題')),
                ('content', models.TextField(verbose_name='代禱內容')),
                ('is_urgent', models.BooleanField(default=False, verbose_name='緊急代禱')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否顯示')),
                ('display_date', models.DateField(default=django.utils.timezone.now, verbose_name='顯示日期')),
            ],
            options={
                'verbose_name': '代禱事項',
                'verbose_name_plural': '代禱事項',
                'ordering': ['-is_urgent', '-display_date'],
            },
        ),
    ]
